print("please enter contdown duration...")
countdown = input("->")
print("please enter the quantity of oxygen tanks you will bring onboard...")
oxygen_tanks = input("->")
print("please enter the amount of food rations you will bring onboard...")
food_rations = input("->")
print("please enter the amount of water rations you will bring onboard...")
water_rations = input("->")
print("Countdown Duration:",countdown,"\nOxygen Tanks:",oxygen_tanks,"\nFood Rations:",food_rations,"\nWater Rations:",water_rations)
print("please confirm your quantity of oxygen tanks...")
oxygen_tanks = input("->")
print("Countdown Duration:",countdown,"\nOxygen Tanks:",oxygen_tanks,"\nFood Rations:",food_rations,"\nWater Rations:",water_rations)